-- Supabase setup (copier/coller dans SQL Editor)

-- 1) Tables
create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  key text unique not null,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.settings (key, value)
values ('global', '{}'::jsonb)
on conflict (key) do nothing;

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  author text not null,
  rating int not null check (rating between 1 and 5),
  text text not null,
  date text,
  order_index int not null default 0,
  created_at timestamptz not null default now()
);

-- 2) RLS (lecture publique, écriture via Edge Function service_role)
alter table public.settings enable row level security;
alter table public.reviews enable row level security;

drop policy if exists "public read settings" on public.settings;
create policy "public read settings"
on public.settings for select
to anon
using (true);

drop policy if exists "public read reviews" on public.reviews;
create policy "public read reviews"
on public.reviews for select
to anon
using (true);

-- 3) Storage
-- Crée un bucket nommé public-images (public) dans Storage.
